# fly.toml app configuration file generated for solutioneers-mcp-server on 2025-12-14T23:02:44+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'solutioneers-mcp-server'
primary_region = 'bom'

[build]
  builtin = "node"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  processes = ["app"]

[processes]
  app = "node http-mcp-server.js"
